name: Lint Plugin Example

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    uses: christophherr/ch-actions/.github/workflows/lint-plugin.yml@main
    with:
      php-version: "8.0"
      node-version: "20"
      skip-php-lint: false
      skip-js-lint: false
      phpcs-standard: "phpcs.xml"
